# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AUPGGPA.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AnnaUniersityGPACalculater(object):
    def setupUi(self, AnnaUniersityGPACalculater):
        AnnaUniersityGPACalculater.setObjectName("AnnaUniersityGPACalculater")
        AnnaUniersityGPACalculater.resize(400, 400)
        AnnaUniersityGPACalculater.setMinimumSize(QtCore.QSize(400, 400))
        AnnaUniersityGPACalculater.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(AnnaUniersityGPACalculater)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(170, 290, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.openGLWidget = QtWidgets.QOpenGLWidget(self.centralwidget)
        self.openGLWidget.setGeometry(QtCore.QRect(-200, 580, 300, 200))
        self.openGLWidget.setObjectName("openGLWidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(60, 30, 61, 241))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.Subject1 = QtWidgets.QLabel(self.splitter)
        self.Subject1.setObjectName("Subject1")
        self.Subject2 = QtWidgets.QLabel(self.splitter)
        self.Subject2.setObjectName("Subject2")
        self.Subject3 = QtWidgets.QLabel(self.splitter)
        self.Subject3.setObjectName("Subject3")
        self.Subject4 = QtWidgets.QLabel(self.splitter)
        self.Subject4.setObjectName("Subject4")
        self.Subject5 = QtWidgets.QLabel(self.splitter)
        self.Subject5.setObjectName("Subject5")
        self.Subject6 = QtWidgets.QLabel(self.splitter)
        self.Subject6.setObjectName("Subject6")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(150, 30, 91, 241))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.comboBox = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox_2 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_4 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_5 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_6 = QtWidgets.QComboBox(self.splitter_2)
        self.comboBox_6.setObjectName("comboBox_6")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setGeometry(QtCore.QRect(270, 30, 61, 241))
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName("splitter_3")
        self.spinBox = QtWidgets.QSpinBox(self.splitter_3)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.splitter_3)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.splitter_3)
        self.spinBox_3.setObjectName("spinBox_3")
        self.spinBox_4 = QtWidgets.QSpinBox(self.splitter_3)
        self.spinBox_4.setObjectName("spinBox_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.splitter_3)
        self.spinBox_5.setObjectName("spinBox_5")
        self.spinBox_6 = QtWidgets.QSpinBox(self.splitter_3)
        self.spinBox_6.setObjectName("spinBox_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 330, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 330, 47, 13))
        self.label_2.setObjectName("label_2")
        AnnaUniersityGPACalculater.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AnnaUniersityGPACalculater)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        AnnaUniersityGPACalculater.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AnnaUniersityGPACalculater)
        self.statusbar.setObjectName("statusbar")
        AnnaUniersityGPACalculater.setStatusBar(self.statusbar)

        self.retranslateUi(AnnaUniersityGPACalculater)
        QtCore.QMetaObject.connectSlotsByName(AnnaUniersityGPACalculater)

    def retranslateUi(self, AnnaUniersityGPACalculater):
        _translate = QtCore.QCoreApplication.translate
        AnnaUniersityGPACalculater.setWindowTitle(_translate("AnnaUniersityGPACalculater", "MainWindow"))
        self.pushButton.setText(_translate("AnnaUniersityGPACalculater", "Calculate"))
        self.Subject1.setText(_translate("AnnaUniersityGPACalculater", "Subject 1"))
        self.Subject2.setText(_translate("AnnaUniersityGPACalculater", "Subject 2"))
        self.Subject3.setText(_translate("AnnaUniersityGPACalculater", "Subject 3"))
        self.Subject4.setText(_translate("AnnaUniersityGPACalculater", "Subject 4"))
        self.Subject5.setText(_translate("AnnaUniersityGPACalculater", "Subject 5"))
        self.Subject6.setText(_translate("AnnaUniersityGPACalculater", "Subject 6"))
        self.label.setText(_translate("AnnaUniersityGPACalculater", "Your Result"))
        self.label_2.setText(_translate("AnnaUniersityGPACalculater", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AnnaUniersityGPACalculater = QtWidgets.QMainWindow()
    ui = Ui_AnnaUniersityGPACalculater()
    ui.setupUi(AnnaUniersityGPACalculater)
    AnnaUniersityGPACalculater.show()
    sys.exit(app.exec_())
